spring.application.name=myproject
# server port 변경
server.port=9091
# DB 연결 url
spring.datasource.url=jdbc:mysql://localhost:3306/sproject
# DB 사용자 아이디
spring.datasource.username=root
# DB 사용자 비밀번호
spring.datasource.password=1234
# Hibernate의 DDL(Data Definition Language) 자동 생성 설정
spring.jpa.hibernate.ddl-auto=update
# Hibernate SQL 쿼리 콘솔에 출력
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#포트원API
portone.imp-key=2216841277266303
portone.imp-secret=LgVHb2tMyp0nqE9XvELX93QZKPiDtdTDRcJ5i8SrE2XfYnhdUb5oHvmaBcfMnJdhwEAYPFwvFB8psrkS
#클라우디너리
cloudinary.cloud-name=p8knze7x
cloudinary.api-key=261783113254841
cloudinary.api-secret=b54wAK2foNrFYOLXxNRkuC7pWPk


# #file upload 경로 관리 
# file.upload-dir=C:/upload/
# #Security 기본 아이디 비밀번호 설정 
# spring.security.user.name=admin
# spring.security.user.password=1234

